# Generated by Django 4.1 on 2022-09-07 13:13

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Note', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last updated')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.DictDocumentMixin),
        ),
        migrations.CreateModel(
            name='AsanaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pict', models.ImageField(height_field='pict_height', help_text='Pictogram 100x100px', max_length=255, upload_to='asana/pict/', width_field='pict_width')),
                ('pict_height', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('pict_width', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='asana.asana')),
            ],
        ),
    ]
