# Generated by Django 4.1 on 2022-09-29 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asanaform',
            name='pict_height',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='asanaform',
            name='pict_width',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='asanaform',
            name='variant',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
