# Generated by Django 4.1 on 2022-09-07 13:13

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Note', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last updated')),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=25)),
                ('minval', models.PositiveIntegerField()),
                ('maxval', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.DictDocumentMixin),
        ),
        migrations.CreateModel(
            name='TaggedUserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Note', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last updated')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.DictDocumentMixin),
        ),
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('taggeduseritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.taggeduseritem')),
                ('img', models.ImageField(upload_to=core.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.taggeduseritem',),
        ),
        migrations.CreateModel(
            name='ScoredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Note', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last updated')),
                ('object_id', models.PositiveIntegerField()),
                ('val', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.score')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.DictDocumentMixin),
        ),
    ]
