# Generated by Django 4.1 on 2022-09-29 07:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceitem',
            name='mark',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lr', 'L,R'), ('x2', 'X 2'), ('x4', 'X 4'), ('dyn', 'dynamic'), ('breath_1', '<1>'), ('breath_2', '<2>'), ('breath_3', '<3>'), ('breath_4', '<4>'), ('breath_5', '<5>'), ('breath_6', '<6>'), ('breath_7', '<7>'), ('breath_8', '<8>'), ('breath_9', '<9>'), ('breath_12', '<12>'), ('breath_18', '<18>'), ('breath_27', '<27>')], help_text='Anything to appear below the image.', max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='sequenceitem',
            name='transitional',
            field=models.BooleanField(default=False, help_text='Transitional items are marked with dashed arrow.'),
        ),
        migrations.CreateModel(
            name='SubSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), help_text='Indises of he first and last items in the sub-sequence.', size=2)),
                ('mark', models.CharField(choices=[('lr', 'L,R'), ('x2', 'X 2'), ('x4', 'X 4'), ('dyn', 'dynamic'), ('breath_1', '<1>'), ('breath_2', '<2>'), ('breath_3', '<3>'), ('breath_4', '<4>'), ('breath_5', '<5>'), ('breath_6', '<6>'), ('breath_7', '<7>'), ('breath_8', '<8>'), ('breath_9', '<9>'), ('breath_12', '<12>'), ('breath_18', '<18>'), ('breath_27', '<27>')], help_text='Sub-sequence mark.', max_length=10)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsequences', to='sequence.sequence')),
            ],
        ),
    ]
